import { StaticImport } from 'next/dist/shared/lib/get-img-props';
import add_icon from '@/public/assets/commons/header/add.png';
import balance_icon from '@/public/assets/commons/header/coin.png';
// Images imported here at the top are used to take advantage of StaticImport types
import user_icon from '@/public/assets/commons/header/defaultIcon.png';
import diamond from '@/public/assets/commons/header/diamond.png';
import game_item_placeholder from '@/public/assets/commons/home/game_item_ph.webp';
import game_platform_placeholder from '@/public/assets/commons/home/game_platform_ph.webp';
import question from '@/public/assets/commons/invite/question.webp';
import bg_login_template from '@/public/assets/commons/login/bg-login-template.webp';
import rescue_fund_icon from '@/public/assets/commons/rescueFund/rescueFund-icon.png';
import vip_bonus_coin from '@/public/assets/commons/vip/bonus-coin.png';
import chat_icon from '@/public/assets/commons/vip/chat_icon.png';
import customer_service from '@/public/assets/commons/vip/cs_icon.png';
import vip_level_guide from '@/public/assets/commons/vip/guide.png';
import fund_lightning from '@/public/assets/commons/vip/lightning.png';
import next_btn from '@/public/assets/commons/vip/next-btn.png';
import prev_btn from '@/public/assets/commons/vip/prev-btn.png';
import { DATA_LANG } from '../constants/enums';

const ASSETS_FOR_EN = `/assets/${DATA_LANG.EN}`;
const ASSETS_FOR_CN = `/assets/${DATA_LANG.CNS}`;
const ASSETS_FOR_IN = `/assets/${DATA_LANG.IND}`;
const ASSETS_FOR_COMMONS = '/assets/commons';

let vip = {};

for (let i = 0; i <= 50; i++) {
  vip = { ...vip, [`vip_${i}`]: `${ASSETS_FOR_COMMONS}/vip/${i}.png` };
}

export const staticImport: Record<string, StaticImport> = {
  user_icon,
  balance_icon,
  diamond,
  add_icon,
  game_item_placeholder,
  game_platform_placeholder,
  bg_login_template,
  chat_icon,
  prev_btn,
  next_btn,
  vip_level_guide,
  fund_lightning,
  vip_bonus_coin,
  customer_service,
  rescue_fund_icon,
  question,
};

export const images: Record<string, string> = {
  // Assets EN
  error_en: `${ASSETS_FOR_EN}/game/error.svg`,
  // Assets CN
  error_cn: `${ASSETS_FOR_CN}/game/error.svg`,
  // Assets IN
  error_in: `${ASSETS_FOR_IN}/game/error.svg`,
  // Assets V2
  ...vip,
  act_claim_bg: `${ASSETS_FOR_COMMONS}/activities/claim_bg.webp`,
  act_cloud_bottom: `${ASSETS_FOR_COMMONS}/activities/cloud-bottom.webp`,
  act_cloud_mission: `${ASSETS_FOR_COMMONS}/activities/cloud_mission.webp`,
  act_current_energy: `${ASSETS_FOR_COMMONS}/activities/energy.png`,
  act_energy_lg: `${ASSETS_FOR_COMMONS}/activities/enegry_lg.webp`,
  act_left_panel: `${ASSETS_FOR_COMMONS}/activities/left_panel.webp`,
  act_panel_btn_active: `${ASSETS_FOR_COMMONS}/activities/btn_activitySelected.png`,
  act_panel_btn_inactive: `${ASSETS_FOR_COMMONS}/activities/btn_activityDefault.png`,
  act_right_panel_activity: `${ASSETS_FOR_COMMONS}/activities/right_panel_activity.webp`,
  act_right_panel_event: `${ASSETS_FOR_COMMONS}/activities/right_panel_event.webp`,
  act_spinner: `${ASSETS_FOR_COMMONS}/activities/snipper.webp`,
  add_to_home: `${ASSETS_FOR_COMMONS}/withdraw_recharge_v2/addToHome.png`,
  afiliado_bg: `${ASSETS_FOR_COMMONS}/footer/afiliado_bg.png`,
  afiliado: `${ASSETS_FOR_COMMONS}/footer/afiliado.png`,
  announcement_close_btn: `${ASSETS_FOR_COMMONS}/close_btn.png`,
  arrow: `${ASSETS_FOR_COMMONS}/convidar/arrow-1.svg`,
  atividade_bg: `${ASSETS_FOR_COMMONS}/footer/atividade_bg.png`,
  atividade: `${ASSETS_FOR_COMMONS}/footer/atividade.webp`,
  autenticacao: `${ASSETS_FOR_COMMONS}/header/autenticacao.png`,
  back_btn: `${ASSETS_FOR_COMMONS}/withdraw_recharge_v2/back-btn.png'`,
  back_v2: `${ASSETS_FOR_COMMONS}/home/back-v2.webp`,
  bank_default_icon: `${ASSETS_FOR_COMMONS}/default-bank-icon.png`,
  refresh_btn: `${ASSETS_FOR_COMMONS}/home/refresh_btn.png`,
  banco_bg: `${ASSETS_FOR_COMMONS}/footer/banco_bg.png`,
  banco: `${ASSETS_FOR_COMMONS}/footer/banco.png`,
  bank_active: `${ASSETS_FOR_COMMONS}/withdraw_recharge_v2/active_state.png`,
  bank_inactive: `${ASSETS_FOR_COMMONS}/withdraw_recharge_v2/inactive_state.webp`,
  bar: `${ASSETS_FOR_COMMONS}/bonusRecharge/bar.png`,
  bg_login_template: `${ASSETS_FOR_COMMONS}/login/bg-login-template.webp`,
  blue_green: `${ASSETS_FOR_COMMONS}/convidar/blueGreen.svg`,
  bonus_close_button: `${ASSETS_FOR_COMMONS}/bonusRecharge/bonus-closeButton.svg`,
  bonus_coin: `${ASSETS_FOR_COMMONS}/header/bonus_coin.png`,
  bonus_submit_button: `${ASSETS_FOR_COMMONS}/bonusRecharge/bonus-submitButton.svg`,
  btn_blue: `${ASSETS_FOR_COMMONS}/announcement/version/btn-blue.png`,
  btn_orange: `${ASSETS_FOR_COMMONS}/announcement/version/btn-orange.png`,
  btn_otp: `${ASSETS_FOR_COMMONS}/login/btnOtp.png`,
  calendar: `${ASSETS_FOR_COMMONS}/invite/recharge/calendar.png`,
  casino_img: `${ASSETS_FOR_COMMONS}/prize_pool/casino.webp`,
  check: `${ASSETS_FOR_COMMONS}/invite/check.svg`,
  checked: `${ASSETS_FOR_COMMONS}/mail/checked.png`,
  chest_icon: `${ASSETS_FOR_COMMONS}/invite/chest-icon.svg`,
  chevron_down: `${ASSETS_FOR_COMMONS}/withdraw_recharge_v2/arrow-down.svg`,
  chevron_icon: `${ASSETS_FOR_COMMONS}/settings/chevron-down-outline.svg`,
  clock_icon: `${ASSETS_FOR_COMMONS}/envelope/clock_icon.png`,
  clock: `${ASSETS_FOR_COMMONS}/bonusRecharge/clock.png`,
  close_btn_maintenance: `${ASSETS_FOR_COMMONS}/maintenance/closeBtn_maintenance.png`,
  close_btn: `${ASSETS_FOR_COMMONS}/close_btn.png`,
  terms_close_btn: `${ASSETS_FOR_COMMONS}/coin-roulette/termsCloseBtn.webp`,
  close_eye: `${ASSETS_FOR_COMMONS}/login/close-eye.png`,
  content_bg: `${ASSETS_FOR_COMMONS}/invite/content-bg.png`,
  copy_btn: `${ASSETS_FOR_COMMONS}/copyIcon.png`,
  copy_icon: `${ASSETS_FOR_COMMONS}/personal_center/copy_icon.png`,
  copy: `${ASSETS_FOR_COMMONS}/copy.svg`,
  cross: `${ASSETS_FOR_COMMONS}/invite/cross.svg`,
  cs_icon1: `${ASSETS_FOR_COMMONS}/vip/cs_icon1.png`,
  db_arrow: `${ASSETS_FOR_COMMONS}/daily_bonus/level-arrow.png`,
  dailyBonus_bg: `${ASSETS_FOR_COMMONS}/daily_bonus/daily_bonus_bg.webp`,
  db_collect_img: `${ASSETS_FOR_COMMONS}/daily_bonus/btn_dbEnabled.webp`,
  db_cur_lvl: `${ASSETS_FOR_COMMONS}/daily_bonus/current_lvl_img.webp`,
  db_ph_coin: `${ASSETS_FOR_COMMONS}/daily_bonus/coin.webp`,
  db_reward_claimable: `${ASSETS_FOR_COMMONS}/daily_bonus/active.webp`,
  db_reward_def: `${ASSETS_FOR_COMMONS}/daily_bonus/default.webp`,
  db_pop_bg: `${ASSETS_FOR_COMMONS}/daily_bonus/pop_bg.webp`,
  default_banner: `${ASSETS_FOR_COMMONS}/home/defaultBanner.webp`,
  default_icon: `${ASSETS_FOR_COMMONS}/header/defaultIcon_v1.png`,
  discount_banner: `${ASSETS_FOR_COMMONS}/loja/discountBanner.png`,
  emoji: `${ASSETS_FOR_COMMONS}/convidar/emoji.svg`,
  exit_modal: `${ASSETS_FOR_COMMONS}/exit_modal.png`,
  eye_off: `${ASSETS_FOR_COMMONS}/eye-off.svg`,
  eye_on: `${ASSETS_FOR_COMMONS}/eye-on.svg`,
  falling_star: `${ASSETS_FOR_COMMONS}/prize_pool/falling-star.webp`,
  first_purchase_btn: `${ASSETS_FOR_COMMONS}/first_purchase/first_purchase_btn.png`,
  game_back: `${ASSETS_FOR_COMMONS}/home/back-button-game.png`,
  game_rule_bg: `${ASSETS_FOR_COMMONS}/rescueFund/gameRule-bg.png`,
  gift_2: `${ASSETS_FOR_COMMONS}/convidar/gift2.svg`,
  gift: `${ASSETS_FOR_COMMONS}/convidar/gift.svg`,
  go_back: `${ASSETS_FOR_COMMONS}/withdraw_recharge_v2/go-back.webp`,
  gold_bottom_bg: `${ASSETS_FOR_COMMONS}/envelope/gold_bottom_bg.png`,
  google_login_btn: `${ASSETS_FOR_COMMONS}/login/google-login-btn.webp`,
  google_login: `${ASSETS_FOR_COMMONS}/login/googleLogin.png`,
  gopay_small_icon: `${ASSETS_FOR_COMMONS}/envelope/gopay_small_icon.png`,
  gopay_xlarge_icon: `${ASSETS_FOR_COMMONS}/envelope/gopay_xlarge_icon.png`,
  guest_login_btn: `${ASSETS_FOR_COMMONS}/login/guest-login-btn.webp`,
  header_autenticacao_bg: `${ASSETS_FOR_COMMONS}/header/autenticacao_bg.png`,
  header_email_bg: `${ASSETS_FOR_COMMONS}/header/email_bg.png`,
  header_refresh_btn: `${ASSETS_FOR_COMMONS}/header/header_refresh_btn.png`,
  header_fundo_bg: `${ASSETS_FOR_COMMONS}/header/fundo_bg.png`,
  header_primeira_bg: `${ASSETS_FOR_COMMONS}/header/primeira_bg.png`,
  header_prize_pool_bg: `${ASSETS_FOR_COMMONS}/header/prizepool_bg.png`,
  header_saque_bg: `${ASSETS_FOR_COMMONS}/header/saque_bg.png`,
  header_suporte_bg: `${ASSETS_FOR_COMMONS}/header/suporte_bg.png`,
  header_jackpot_bg: `${ASSETS_FOR_COMMONS}/header/jackpot_bg.png`,
  header_btn_stage: `${ASSETS_FOR_COMMONS}/header/stage.png`,
  icon_cs: `${ASSETS_FOR_COMMONS}/header/icon_cs.png`,
  image_background: `${ASSETS_FOR_COMMONS}/convidar/image-background.svg`,
  inside_box: `${ASSETS_FOR_COMMONS}/withdraw_recharge_v2/inside-box.webp'`,
  ios_loader: `${ASSETS_FOR_COMMONS}/ios-loader.webp`,
  loader: `${ASSETS_FOR_COMMONS}/loader.gif`,
  login_bg: `${ASSETS_FOR_COMMONS}/login/login-bg.webp`,
  login_btn: `${ASSETS_FOR_COMMONS}/login/loginBtn.png`,
  login_img_china: `${ASSETS_FOR_COMMONS}/login/img_china.png`,
  login_img_eng: `${ASSETS_FOR_COMMONS}/login/img_eng.png`,
  login_img_indo: `${ASSETS_FOR_COMMONS}/login/img_indo.png`,
  loja_bg: `${ASSETS_FOR_COMMONS}/footer/loja_bg.png`,
  loja_chevron_down: `${ASSETS_FOR_COMMONS}/loja/chevronDown.png`,
  loja_close_button: `${ASSETS_FOR_COMMONS}/loja/Loja-closeButton.png`,
  loja_coin: `${ASSETS_FOR_COMMONS}/loja/coin.webp`,
  loja_list_bg: `${ASSETS_FOR_COMMONS}/loja/Loja-ListBg.png`,
  loja_submit: `${ASSETS_FOR_COMMONS}/loja/Loja-Btn.webp`,
  loja: `${ASSETS_FOR_COMMONS}/footer/loja.png`,
  mail: `${ASSETS_FOR_COMMONS}/header/mail.png`,
  main_bg_web_portrait: `${ASSETS_FOR_COMMONS}/home/main_bg_web_portrait.webp`,
  max_claimed: `${ASSETS_FOR_COMMONS}/vip/maxClaimed.png`,
  mobile_login_btn: `${ASSETS_FOR_COMMONS}/login/mobile-login-btn.webp`,
  modal_close_btn: `${ASSETS_FOR_COMMONS}/home/modal-close.svg`,
  money: `${ASSETS_FOR_COMMONS}/convidar/money.svg`,
  mt: `${ASSETS_FOR_COMMONS}/home/mt.png`,
  music_icon: `${ASSETS_FOR_COMMONS}/settings/icon_music.png`,
  no_check: `${ASSETS_FOR_COMMONS}/rescueFund/onCheck.png`,
  no_data_icon: `${ASSETS_FOR_COMMONS}/withdraw_recharge_v2/noDataImg.png`,
  no_data: `${ASSETS_FOR_COMMONS}/withdraw_recharge_v2/no-da.png`,
  not_collected_icon: `${ASSETS_FOR_COMMONS}/daily_bonus/not-collected.png`,
  open_eye: `${ASSETS_FOR_COMMONS}/login/open-eye.png`,
  payment_backdrop: `${ASSETS_FOR_COMMONS}/loja/backdrop.png`,
  payment_board: `${ASSETS_FOR_COMMONS}/loja/paymentBoard.png`,
  platform_active_btn: `${ASSETS_FOR_COMMONS}/announcement/platform/active-btn.png`,
  platform_btn: `${ASSETS_FOR_COMMONS}/announcement/platform/btn.png`,
  platform_content: `${ASSETS_FOR_COMMONS}/announcement/platform/content.png`,
  platform_sidebar: `${ASSETS_FOR_COMMONS}/announcement/platform/sidebar.png`,
  price_bag: `${ASSETS_FOR_COMMONS}/coin-roulette/price-bag.png`,
  price_envelope: `${ASSETS_FOR_COMMONS}/coin-roulette/price-envelope.png`,
  price_giftbox: `${ASSETS_FOR_COMMONS}/coin-roulette/price-giftbox.png`,
  primeira_close: `${ASSETS_FOR_COMMONS}/first_purchase/primeira_close.png`,
  primeira_tips: `${ASSETS_FOR_COMMONS}/first_purchase/Primeira-tipsButton.png`,
  primeira: `${ASSETS_FOR_COMMONS}/header/primeira.png`,
  prize_pool_bg: `${ASSETS_FOR_COMMONS}/prize_pool/prize-bg.png`,
  prize_pool_close_btn: `${ASSETS_FOR_COMMONS}/prize_pool/closeButton.png`,
  prize_pool: `${ASSETS_FOR_COMMONS}/header/prize_pool.png`,
  profile_border: `${ASSETS_FOR_COMMONS}/personal_center/profile_border.webp`,
  profile_copy_icon: `${ASSETS_FOR_COMMONS}/profile/copy-icon.png`,
  profile_effects_icon: `${ASSETS_FOR_COMMONS}/profile/effects-icon.png`,
  profile_error_icon: `${ASSETS_FOR_COMMONS}/profile/error-icon.png`,
  profile_music_icon: `${ASSETS_FOR_COMMONS}/profile/music-icon.png`,
  profile_sms_icon: `${ASSETS_FOR_COMMONS}/profile/SMS.webp`,
  profile_whatsAPP_icon: `${ASSETS_FOR_COMMONS}/profile/whatsApp.webp`,
  qrcode: `${ASSETS_FOR_COMMONS}/invite/qrcode.svg`,
  rays: `${ASSETS_FOR_COMMONS}/coin-roulette/rays.png`,
  read: `${ASSETS_FOR_COMMONS}/mail/read.png`,
  record_coins: `${ASSETS_FOR_COMMONS}/invite/record-coins.svg`,
  record_person: `${ASSETS_FOR_COMMONS}/invite/record-person.svg`,
  records_bg: `${ASSETS_FOR_COMMONS}/withdraw_recharge_v2/records-bg_v1.webp'`,
  rescue_fund_title_pt: `${ASSETS_FOR_COMMONS}/rescueFund/rescue-fund-title-pt.png`,
  rescue_fund_title_zh_tw: `${ASSETS_FOR_COMMONS}/rescueFund/rescue-fund-title-zh-tw.png`,
  rescue_fund: `${ASSETS_FOR_COMMONS}/header/rescue_fund.png`,
  roulette_pointer: `${ASSETS_FOR_COMMONS}/coin-roulette/roulettePointer.png`,
  roulette_wheel_with_icons: `${ASSETS_FOR_COMMONS}/coin-roulette/roulletteWheelWithIcons.png`,
  rp_icon: `${ASSETS_FOR_COMMONS}/bonusRecharge/rp_icon.png`,
  saque: `${ASSETS_FOR_COMMONS}/header/saque.png`,
  search: `${ASSETS_FOR_COMMONS}/login/search.png`,
  selected: `${ASSETS_FOR_COMMONS}/mail/selected.png`,
  settings_btn_close: `${ASSETS_FOR_COMMONS}/settings/btn_close.png`,
  snow_1: `${ASSETS_FOR_COMMONS}/vip/snow1.png`,
  snow_2: `${ASSETS_FOR_COMMONS}/vip/snow2.png`,
  snow_3: `${ASSETS_FOR_COMMONS}/vip/snow3.png`,
  sound_icon: `${ASSETS_FOR_COMMONS}/settings/icon_volume.png`,
  sparkles: `${ASSETS_FOR_COMMONS}/coin-roulette/sparkles.png`,
  star_img: `${ASSETS_FOR_COMMONS}/prize_pool/star.webp`,
  starts_img: `${ASSETS_FOR_COMMONS}/prize_pool/starts.webp`,
  submit_btn: `${ASSETS_FOR_COMMONS}/withdraw_recharge_v2/submit-btn_v1.png`,
  suporte: `${ASSETS_FOR_COMMONS}/header/suporte.png`,
  support_bg: `${ASSETS_FOR_COMMONS}/support/supportBg.webp`,
  support_chat: `${ASSETS_FOR_COMMONS}/support/support-chat.png`,
  support_close: `${ASSETS_FOR_COMMONS}/support/support-CloseBtn.webp`,
  support_icon: `${ASSETS_FOR_COMMONS}/support/supportIcon.webp`,
  tier_cn: `${ASSETS_FOR_COMMONS}/invite/tier-cn.svg`,
  tier_en: `${ASSETS_FOR_COMMONS}/invite/tier-en.svg`,
  tier_in: `${ASSETS_FOR_COMMONS}/invite/tier-in.svg`,
  tips_bg: `${ASSETS_FOR_COMMONS}/first_purchase/Primeira-tipsBg.webp`,
  today_losses_bg: `${ASSETS_FOR_COMMONS}/rescueFund/todayLosses-bg.png`,
  unchecked: `${ASSETS_FOR_COMMONS}/mail/unchecked.png`,
  unread: `${ASSETS_FOR_COMMONS}/mail/unread.png`,
  unselected: `${ASSETS_FOR_COMMONS}/mail/unselected.png`,
  version_bg: `${ASSETS_FOR_COMMONS}/announcement/version/bg.png`,
  vip_bg: `${ASSETS_FOR_COMMONS}/footer/vip_bg.png`,
  vip: `${ASSETS_FOR_COMMONS}/footer/vip.png`,
  warning: `${ASSETS_FOR_COMMONS}/warning.svg`,
  withdraw_pass_bg: `${ASSETS_FOR_COMMONS}/withdraw_recharge_v2/withdrawal-password-bg.webp`,
  x_button: `${ASSETS_FOR_COMMONS}/withdraw_recharge_v2/XBUTTON.png`,
  yellow_circle_red_check: `${ASSETS_FOR_COMMONS}/envelope/yellow_circle_red_check.png`,
  yellow: `${ASSETS_FOR_COMMONS}/convidar/yellow.svg`,
  yesterday_losses_bg: `${ASSETS_FOR_COMMONS}/rescueFund/yesterdayLosses-bg.png`,
  footer_activity: `${ASSETS_FOR_COMMONS}/footer/img_activity.png`,
  footer_vip: `${ASSETS_FOR_COMMONS}/footer/img_vip.png`,
  footer_bonus: `${ASSETS_FOR_COMMONS}/footer/img_bonus.png`,
  footer_affiliate: `${ASSETS_FOR_COMMONS}/footer/img_afiliate.png`,
  footer_withdraw: `${ASSETS_FOR_COMMONS}/footer/img_withdraw.png`,
  footer_deposit: `${ASSETS_FOR_COMMONS}/footer/img_deposit.png`,
  icon_first_recharge: `${ASSETS_FOR_COMMONS}/header/icon_first_recharge.png`,
  icon_rescue_fund: `${ASSETS_FOR_COMMONS}/header/icon_rescue_fund.png`,
  icon_bind_phone: `${ASSETS_FOR_COMMONS}/header/icon_bind_phone.png`,
  icon_download: `${ASSETS_FOR_COMMONS}/header/download.png`,
  icon_settings: `${ASSETS_FOR_COMMONS}/header/icon_settings.png`,
  icon_mail: `${ASSETS_FOR_COMMONS}/header/icon_mail.png`,
  icon_coin: `${ASSETS_FOR_COMMONS}/header/coin.png`,
  first_purchase_battery: `${ASSETS_FOR_COMMONS}/first_purchase/first_purchase_battery.png`,
  avatar_border: `${ASSETS_FOR_COMMONS}/personal_center/avatar-border.png`,
  left_panel: `${ASSETS_FOR_COMMONS}/withdraw_recharge_v2/bg_paymentSidebar.webp`,
  discount_tag: `${ASSETS_FOR_COMMONS}/withdraw_recharge_v2/discount_tag.webp`,
  recommended_en: `${ASSETS_FOR_EN}/withdraw_recharge_v2/recommended.webp`,
  recommended_in: `${ASSETS_FOR_IN}/withdraw_recharge_v2/recommended.webp`,
  recommended_cn: `${ASSETS_FOR_CN}/withdraw_recharge_v2/recommended.webp`,
  ice_arrow: `${ASSETS_FOR_COMMONS}/withdraw_recharge_v2/ice-arrow.png`,
  opened_eye: `${ASSETS_FOR_COMMONS}/withdraw_recharge_v2/opened-eye.png`,
  closed_eye: `${ASSETS_FOR_COMMONS}/withdraw_recharge_v2/closed-eye.png`,
  scroll_indicator: `${ASSETS_FOR_COMMONS}/withdraw_recharge_v2/scroll-indicator.webp`,
  headline: `${ASSETS_FOR_COMMONS}/withdraw_recharge_v2/rightPanel_headline.png`,
  records_icon: `${ASSETS_FOR_COMMONS}/withdraw_recharge_v2/records.png`,
  winnerBanner: `${ASSETS_FOR_COMMONS}/home/winnerBanner.png`,
  rechargeBonusBG: `${ASSETS_FOR_COMMONS}/home/rechargeBonusBG.png`,
  rechargePopupBG: `${ASSETS_FOR_COMMONS}/home/rechargePopupBg.png`,
  RechargePopupTitle: `${ASSETS_FOR_COMMONS}/home/RechargePopupTitle.png`,
  RechargePopupEffect: `${ASSETS_FOR_COMMONS}/home/recgargePopupEffect.png`,
  redCloseBtn: `${ASSETS_FOR_COMMONS}/home/redCloseButton.png`,
  bonusRechargeText: `${ASSETS_FOR_COMMONS}/home/bonusRechargeText.png`,
  countdownFrame: `${ASSETS_FOR_COMMONS}/home/countdownFrame.png`,
  countdownClock: `${ASSETS_FOR_COMMONS}/home/countdownClock.png`,
  coins: `${ASSETS_FOR_COMMONS}/home/coin1.png`,
  discounted: `${ASSETS_FOR_COMMONS}/home/discounted.png`,
  settings_logout: `${ASSETS_FOR_COMMONS}/settings/logoutIcon.png`,
  settings_clear_cache: `${ASSETS_FOR_COMMONS}/settings/clearCacheIcon.png`,

  // SVGA
  coin_burst_animation: `${ASSETS_FOR_EN}/envelope/CoinBurstAnimation.svga`,
  coin_drop_float: `${ASSETS_FOR_EN}/envelope/CoinDropFloat.svga`,
  coin_drop_progressbar: `${ASSETS_FOR_EN}/envelope/CoinDropProgressBar.svga`,
  glass_dome_animation: `${ASSETS_FOR_EN}/envelope/GlassDomeAnimation.svga`,
  glass_dome_web: `${ASSETS_FOR_EN}/envelope/GlassDomeWeb.svga`,
  glow_text_bg: `${ASSETS_FOR_EN}/envelope/GlowTextBG.svga`,
  orange_chip: `${ASSETS_FOR_EN}/envelope/OrangeChip.svga`,
  red_envelope_001a: `${ASSETS_FOR_EN}/envelope/RedEnvelope001a.svga`,
  red_envelope_002a: `${ASSETS_FOR_EN}/envelope/RedEnvelope002a.svga`,
  svga_10: `${ASSETS_FOR_EN}/envelope/svga_10.svga`,
  svga_11: `${ASSETS_FOR_EN}/envelope/svga_11.svga`,
  svga_12: `${ASSETS_FOR_EN}/envelope/svga_12.svga`,
  svga_5: `${ASSETS_FOR_EN}/envelope/svga_5.svga`,
  svga_6: `${ASSETS_FOR_EN}/envelope/svga_6.svga`,
  svga_7: `${ASSETS_FOR_EN}/envelope/svga_7.svga`,
  svga_8: `${ASSETS_FOR_EN}/envelope/svga_8.svga`,
  svga_9: `${ASSETS_FOR_EN}/envelope/svga_9.svga`,
  svga_afiliado_icon: `${ASSETS_FOR_COMMONS}/footer/afiliado_icon.svga`,
  svga_atividade_icon: `${ASSETS_FOR_COMMONS}/footer/atividade_icon.svga`,
  svga_autenticacao_icon: `${ASSETS_FOR_COMMONS}/header/autenticacao_icon.svga`,
  svga_banco_icon: `${ASSETS_FOR_COMMONS}/footer/banco_icon.svga`,
  svga_bonus: `${ASSETS_FOR_COMMONS}/bonus/bonus.svga`,
  svga_convidar: `${ASSETS_FOR_COMMONS}/convidar/convidar.svga`,
  svga_email_icon: `${ASSETS_FOR_COMMONS}/header/email_icon.svga`,
  svga_first_purchase: `${ASSETS_FOR_COMMONS}/first_purchase/first_purchase.svga`,
  svga_fundo_icon: `${ASSETS_FOR_COMMONS}/header/fundo_icon.svga`,
  svga_loja_board: `${ASSETS_FOR_COMMONS}/loja/Loja-Board.svga`,
  svga_loja_character: `${ASSETS_FOR_COMMONS}/loja/Loja_Character.svga`,
  svga_loja_coins: `${ASSETS_FOR_COMMONS}/loja/coins-loja.svga`,
  svga_loja_icon: `${ASSETS_FOR_COMMONS}/footer/loja_icon.svga`,
  svga_main_bg: `${ASSETS_FOR_COMMONS}/home/main_bg.svga`,
  svga_pp_coins: `${ASSETS_FOR_COMMONS}/prize_pool/pp-coins.svga`,
  svga_primeira_icon: `${ASSETS_FOR_COMMONS}/header/primeira_icon.svga`,
  svga_prizepool_icon: `${ASSETS_FOR_COMMONS}/header/prizepool_icon.svga`,
  svga_profile_bg: `${ASSETS_FOR_COMMONS}/profile/profile-bg.svga`,
  svga_saque_icon: `${ASSETS_FOR_COMMONS}/header/saque_icon.svga`,
  svga_suporte_icon: `${ASSETS_FOR_COMMONS}/header/suporte_icon.svga`,
  svga_vip_icon: `${ASSETS_FOR_COMMONS}/footer/vip_icon.svga`,
  coins_treasure: `${ASSETS_FOR_COMMONS}/envelope/coinsTreasure.svga`,
} as const;

export const audio: Record<string, string> = {
  mp3_music: `${ASSETS_FOR_COMMONS}/profile/music.mp3`,
  plastic_bubble_click: `${ASSETS_FOR_COMMONS}/profile/plastic-bubble-click.wav`,
} as const;
